#! /bin/bash

if [ -f mkrelease ] ; then
	cd ..
fi

if [ -d bin ] ; then
	cd ..
fi

ORIGDIR=`pwd`
TMPDIR=${ORIGDIR}/mkrelease.$$

# Prompt for release number
RESULT=1
while [ ${RESULT} -eq 1 ] ; do
	echo ""
	echo -n "Release number? "
	read RELEASENUM crap

	if [ "${RELEASENUM}" != "" ] ; then
		RESULT=0
	else
		echo "Idiot.  Enter the release number!"
	fi
done

# Make the new configure.ac
scripts/tagversion -R ${RELEASENUM}

# Check everything in (from above web & bot)
git add -u
git commit

# Create the tag
git tag -m "Tagging release ${RELEASENUM}" -u F0B5CC69 v${RELEASENUM}

# Create a temp dir to export in
mkdir ${TMPDIR}

# Check out the tagged release
git archive --format=tar --prefix=beirdobot-${RELEASENUM} v${RELEASENUM} | \
	( cd ${TMPDIR} && tar xf -)
cd ${TMPDIR}/beirdobot-${RELEASENUM}

# Make the release.h
scripts/tagversion -r ${RELEASENUM}

# Generate the ChangeLog
scripts/gitlog2changelog.py

cd ${TMPDIR}

# Create a tarball as beirdobot-${RELEASENUM}
tar -czvf beirdobot-${RELEASENUM}.tar.gz  beirdobot-${RELEASENUM}
cp beirdobot-${RELEASENUM}.tar.gz ${ORIGDIR}

# (future) Create an RPM
# (future) Create a DEB

# Clean up the checked out dir
cd ${ORIGDIR}
rm -rf ${TMPDIR}

# Make the new configure.ac
scripts/tagversion -R ${RELEASENUM}+GIT
git add -u
git commit -m "Post-release tagging for configure.ac"

